version = 0.1
[default]
[default.global]
[default.global.parameters]
stack_name = "bedrock-proxy-dev"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "bedrock-proxy"
region = "us-east-1"
image_repositories = []

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"
port = 3000

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "bedrock-proxy-prod"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "bedrock-proxy"
region = "us-east-1"
image_repositories = []
parameter_overrides = "Environment=\"production\" DeploymentType=\"CANARY\"" 