AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway resources for Bedrock OpenAI-compatible proxy

Resources:
  BedrockProxyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      EndpointConfiguration: 
        Type: REGIONAL
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          Description: Usage plan for Bedrock Proxy API
          Quota:
            Limit: 10000
            Period: MONTH
          Throttle:
            BurstLimit: 100
            RateLimit: 50
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          MetricsEnabled: true
          DataTraceEnabled: true
          LoggingLevel: INFO 