AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for Bedrock OpenAI-compatible proxy

Resources:
  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub bedrock-proxy-accounts-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: accountId
          AttributeType: S
        - AttributeName: apiKey
          AttributeType: S
      KeySchema:
        - AttributeName: accountId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ApiKeyIndex
          KeySchema:
            - AttributeName: apiKey
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub bedrock-proxy-sessions-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub bedrock-proxy-cache-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: cacheKey
          AttributeType: S
      KeySchema:
        - AttributeName: cacheKey
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment 