name: Run Tests

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - '**'
      - '!main'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm run test:unit
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage
          path: coverage
          
  integration-tests:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TEST_ACCOUNT_ID: ${{ secrets.TEST_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start mock services
        run: npm run mock:start
        
      - name: Run integration tests
        run: npm run test:integration
        
      - name: Stop mock services
        if: always()
        run: npm run mock:stop 